### ISSUE TITLE
iPhone 安全区样式与兼容问题

### ISSUE THREAD

**Issue by imfenghuang** [imfenghuang/blog#27]
从 iPhone X 开始，前端又多了一项"兼容"工作，好在 iOS 已经提供了兼容方案。
```html
<meta name="viewport" content="viewport-fit:cover">

<style>
.safe-style{
  padding-bottom:  constant(safe-area-inset-bottom);
  padding-bottom:  env(safe-area-inset-bottom);
}
</style>
```
上述样式在安卓端，因为无法识别而被忽略。
但是，当你这样写：
```css
.safe-style{
  padding: 20px 0;
  padding-bottom:  constant(safe-area-inset-bottom);
  padding-bottom:  env(safe-area-inset-bottom);
}
```
构建工具可能会帮上倒忙，因为构建工具在输出样式时，会把分开写的样式，合并成一条。比如：
```css
padding: 20px 0  env(safe-area-inset-bottom);
```
此时，在一些安卓手机上，就会出现无法识别和解析 `padding` 的情况，导致页面显示错误。

解决办法：
1. 阻止此处样式合并；
2. 单独一层元素，如 `div` 来设置安全区样式；
